# Generated by Django 5.0.6 on 2024-05-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='staticfiles/team-avatars/'),
        ),
    ]
