# Generated by Django 5.0.6 on 2024-06-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='tfug_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
