# Generated by Django 5.0.6 on 2024-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_url_tfug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='tfug_url',
            field=models.URLField(blank=True),
        ),
    ]
