# Generated by Django 5.0.6 on 2024-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('registration_link', models.URLField()),
                ('collaboration_link', models.URLField()),
                ('sponsorship_link', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
