# Generated by Django 5.0.6 on 2024-05-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='collaboration_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsorship_link',
            field=models.URLField(blank=True),
        ),
    ]
