# Generated by Django 5.0.6 on 2024-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_speakers_topic_event_speakers_speakerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='speakers',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakers',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakers',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakers',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
