# Generated by Django 5.0.6 on 2024-05-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_speakers_email_speakers_github_speakers_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='staticfiles/events/'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(upload_to='staticfiles/speakers/'),
        ),
    ]
