# Generated by Django 5.0.6 on 2024-05-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_image_alter_speakers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(upload_to='speakers/'),
        ),
    ]
